import type { CiSetupOptions, DetectResult, GeneratedFile } from './types.js';

const LICENSE_NOTICE = '# License: PolyForm-Noncommercial-1.0.0 — confirm non-commercial use';
const COMMERCIAL_NOTICE =
  '# ⚠ COMMERCIAL USE: verify PolyForm-Noncommercial-1.0.0 license before deploying to client environments.';
const GENERATED_NOTICE = '# Generated by: gitnexus ci-setup';

// The port gitnexus serve always binds inside the container/image (the host or
// proxy-facing port is derived from opts.port). Keep these in one place so the
// port contract can't drift across the generated artifacts.
const CONTAINER_PORT = 4747;
const GITNEXUS_IMAGE = 'ghcr.io/abhigyanpatwari/gitnexus:latest';

/** The Caddy reverse-proxy port (one above the gitnexus serve port). */
function caddyProxyPort(opts: CiSetupOptions): number {
  return opts.port + 1;
}

function buildGitHubActionsWorkflow(opts: CiSetupOptions): string {
  const onBlock =
    opts.branchStrategy === 'pr-scoped'
      ? `on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]`
      : `on:
  push:
    branches: [main]`;

  return `${LICENSE_NOTICE}
${GENERATED_NOTICE}

name: GitNexus Index

${onBlock}

permissions:
  contents: read

concurrency:
  group: gitnexus-$\{{ github.ref }}
  cancel-in-progress: true

jobs:
  gitnexus-index:
    name: Index repository
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Analyze repository
        run: npx gitnexus@${opts.version} analyze --skills

      - name: Upload index artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitnexus-index-\${{ github.sha }}
          path: .gitnexus/
          retention-days: 30

      - name: Verify index was produced
        run: |
          if [ -f .gitnexus/meta.json ]; then
            echo "✓ GitNexus index updated at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          else
            echo "✗ GitNexus index not found" && exit 1
          fi
`;
}

function buildAzurePipelineYaml(opts: CiSetupOptions): string {
  const trigger =
    opts.branchStrategy === 'pr-scoped'
      ? `trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'`
      : `trigger:
  branches:
    include:
      - main

pr: none`;

  return `${COMMERCIAL_NOTICE}
${GENERATED_NOTICE}

${trigger}

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 0

  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Set up Node.js 22'

  - script: npx gitnexus@${opts.version} analyze --skills
    displayName: 'Analyze repository'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '.gitnexus'
      artifact: 'gitnexus-index'
      publishLocation: 'pipeline'
    displayName: 'Upload index artifact'

  - script: |
      if [ -f .gitnexus/meta.json ]; then
        echo "✓ GitNexus index updated"
      else
        echo "✗ GitNexus index not found" && exit 1
      fi
    displayName: 'Verify index was produced'
`;
}

function buildDockerComposeTokenAuth(opts: CiSetupOptions): string {
  return `${LICENSE_NOTICE}
${GENERATED_NOTICE}
#
# Auth model: Caddy reverse proxy enforces GITNEXUS_TOKEN.
# The gitnexus service is NOT published — only the proxy port is reachable.
#
# Required environment variables (create a .env file or set in your shell):
#   GITNEXUS_TOKEN=<your-secret-token>
#   WORKSPACE_DIR=<path-to-repos>  (default: ./workspace)

services:
  gitnexus:
    image: ${GITNEXUS_IMAGE}
    # No ports: — gitnexus is accessible only to the proxy on the internal network.
    volumes:
      - gitnexus-data:/data/gitnexus
      - \${WORKSPACE_DIR:-./workspace}:/workspace:ro
    environment:
      GITNEXUS_HOME: /data/gitnexus
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${CONTAINER_PORT}/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  gitnexus-proxy:
    image: caddy:alpine
    ports:
      - "\${GITNEXUS_PROXY_PORT:-${caddyProxyPort(opts)}}:${caddyProxyPort(opts)}"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      GITNEXUS_TOKEN: \${GITNEXUS_TOKEN:?GITNEXUS_TOKEN is required}
    depends_on:
      gitnexus:
        condition: service_healthy
    restart: unless-stopped

volumes:
  gitnexus-data:
`;
}

function buildDockerComposeNoAuth(opts: CiSetupOptions): string {
  return `${LICENSE_NOTICE}
${GENERATED_NOTICE}
#
# ⚠ NO AUTH — trusted internal network only.
# Anyone who can reach port ${opts.port} has full access to all indexed repositories.
# Do not expose this port to the public internet.

services:
  gitnexus:
    image: ${GITNEXUS_IMAGE}
    ports:
      - "\${GITNEXUS_PORT:-${opts.port}}:${CONTAINER_PORT}"
    volumes:
      - gitnexus-data:/data/gitnexus
      - \${WORKSPACE_DIR:-./workspace}:/workspace:ro
    environment:
      GITNEXUS_HOME: /data/gitnexus
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${CONTAINER_PORT}/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  gitnexus-data:
`;
}

function buildDockerCompose(opts: CiSetupOptions): string {
  return opts.auth === 'token' ? buildDockerComposeTokenAuth(opts) : buildDockerComposeNoAuth(opts);
}

function buildCaddyfile(opts: CiSetupOptions): string {
  const proxyPort = caddyProxyPort(opts);
  return `:${proxyPort} {
    @authorized header Authorization "Bearer {env.GITNEXUS_TOKEN}"

    handle @authorized {
        reverse_proxy gitnexus:${CONTAINER_PORT}
    }

    respond "Unauthorized" 401
}
`;
}

function buildAcaDeployScript(opts: CiSetupOptions): string {
  const authComment =
    opts.auth === 'token'
      ? `# Auth: enable Azure Container Apps built-in authentication (Easy Auth) for token enforcement.
# In the Azure portal, go to your Container App → Settings → Authentication → Add Identity Provider.`
      : `# ⚠ NO AUTH configured. Restrict access via Azure Container Apps ingress settings
# or use Easy Auth (Azure portal → Authentication) before exposing to users.`;

  return `#!/usr/bin/env bash
# ${COMMERCIAL_NOTICE.slice(2)}
# ${GENERATED_NOTICE.slice(2)}
#
# Deploy GitNexus as an Azure Container App.
# Requires: az CLI, logged in with Contributor on the target resource group.
#
# ${authComment}

set -euo pipefail

RESOURCE_GROUP="\${RESOURCE_GROUP:-gitnexus-rg}"
LOCATION="\${LOCATION:-eastus}"
ENVIRONMENT="\${CONTAINER_APP_ENV:-gitnexus-env}"
APP_NAME="\${APP_NAME:-gitnexus}"
STORAGE_ACCOUNT="\${STORAGE_ACCOUNT:-gitnexusstorage}"
FILE_SHARE="\${FILE_SHARE:-gitnexus-data}"

echo "Creating resource group..."
az group create --name "\$RESOURCE_GROUP" --location "\$LOCATION"

echo "Creating storage account for persistent index..."
az storage account create \\
  --name "\$STORAGE_ACCOUNT" \\
  --resource-group "\$RESOURCE_GROUP" \\
  --location "\$LOCATION" \\
  --sku Standard_LRS

az storage share-rm create \\
  --name "\$FILE_SHARE" \\
  --storage-account "\$STORAGE_ACCOUNT" \\
  --resource-group "\$RESOURCE_GROUP"

echo "Creating Container Apps environment..."
az containerapp env create \\
  --name "\$ENVIRONMENT" \\
  --resource-group "\$RESOURCE_GROUP" \\
  --location "\$LOCATION"

echo "Mounting Azure Files into the environment..."
STORAGE_KEY=\$(az storage account keys list \\
  --account-name "\$STORAGE_ACCOUNT" \\
  --resource-group "\$RESOURCE_GROUP" \\
  --query "[0].value" -o tsv)

az containerapp env storage set \\
  --name "\$ENVIRONMENT" \\
  --resource-group "\$RESOURCE_GROUP" \\
  --storage-name gitnexus-data \\
  --azure-file-account-name "\$STORAGE_ACCOUNT" \\
  --azure-file-account-key "\$STORAGE_KEY" \\
  --azure-file-share-name "\$FILE_SHARE" \\
  --access-mode ReadWrite

echo "Deploying GitNexus container app..."
az containerapp create \\
  --name "\$APP_NAME" \\
  --resource-group "\$RESOURCE_GROUP" \\
  --environment "\$ENVIRONMENT" \\
  --image ${GITNEXUS_IMAGE} \\
  --target-port ${CONTAINER_PORT} \\
  --ingress internal \\
  --env-vars "GITNEXUS_HOME=/data/gitnexus" \\
  --volume-name gitnexus-data \\
  --volume-storage-type AzureFile \\
  --volume-storage-name gitnexus-data \\
  --mount-path /data/gitnexus

echo "Done. Container App URL:"
az containerapp show \\
  --name "\$APP_NAME" \\
  --resource-group "\$RESOURCE_GROUP" \\
  --query "properties.configuration.ingress.fqdn" -o tsv
`;
}

function buildMcpSnippet(opts: CiSetupOptions): string {
  const proxyPort = opts.auth === 'token' ? opts.port + 1 : opts.port;
  const urlComment =
    opts.auth === 'token'
      ? `  // Proxy port (Caddy enforces GITNEXUS_TOKEN). Change <GITNEXUS_HOST> to the server's IP or hostname.`
      : `  // Direct gitnexus port (no auth). Change <GITNEXUS_HOST> to the server's IP or hostname.`;

  const headersBlock =
    opts.auth === 'token'
      ? `,
      "headers": {
        "Authorization": "Bearer YOUR_GITNEXUS_TOKEN"
      }`
      : '';

  const commentLine = urlComment.replace(/^\s*\/\/\s*/, '').trim();
  return `{
  "_comment": "${commentLine}",
  "_note": "Merge into ~/.claude/settings.json mcpServers block. Verify the exact Claude Code HTTP MCP entry format against current docs before applying.",
  "mcpServers": {
    "gitnexus": {
      "type": "http",
      "url": "http://<GITNEXUS_HOST>:${proxyPort}/api/mcp"${headersBlock}
    }
  }
}
`;
}

function buildGitnexusMd(opts: CiSetupOptions, detect: DetectResult): string {
  const ciLabel = {
    'github-actions': 'GitHub Actions',
    'azure-devops': 'Azure DevOps',
    both: 'GitHub Actions + Azure DevOps',
  }[opts.ci];

  const deployLabel = {
    docker: 'Docker Compose',
    'azure-container-app': 'Azure Container App',
    both: 'Docker Compose + Azure Container App',
  }[opts.deploy];

  const authLabel =
    opts.auth === 'token'
      ? 'Caddy reverse proxy enforces `GITNEXUS_TOKEN` bearer token'
      : '⚠ No auth — trusted internal network only';

  const branchLabel =
    opts.branchStrategy === 'pr-scoped' ? 'Main branch + all open PRs' : 'Main branch only';

  const connectSection =
    opts.auth === 'token'
      ? `### Claude Code

Copy the MCP entry from \`.claude/gitnexus-mcp-snippet.json\` into \`~/.claude/settings.json\`:

\`\`\`json
"mcpServers": {
  "gitnexus": {
    "type": "http",
    "url": "http://<GITNEXUS_HOST>:${caddyProxyPort(opts)}/api/mcp",
    "headers": {
      "Authorization": "Bearer YOUR_GITNEXUS_TOKEN"
    }
  }
}
\`\`\`

Replace \`<GITNEXUS_HOST>\` with the server's IP or hostname. Set \`GITNEXUS_TOKEN\` to the same value used when starting the server.

### Cursor

Add to \`~/.cursor/mcp.json\` under \`mcpServers\`:

\`\`\`json
"gitnexus": {
  "command": "npx",
  "args": ["-y", "gitnexus@${opts.version}", "mcp"],
  "env": {}
}
\`\`\`

*Or* point Cursor at the shared HTTP server using the same \`type: http\` entry as Claude Code.`
      : `### Claude Code

Copy the MCP entry from \`.claude/gitnexus-mcp-snippet.json\` into \`~/.claude/settings.json\`:

\`\`\`json
"mcpServers": {
  "gitnexus": {
    "type": "http",
    "url": "http://<GITNEXUS_HOST>:${opts.port}/api/mcp"
  }
}
\`\`\`

Replace \`<GITNEXUS_HOST>\` with the server's IP or hostname.`;

  const dockerDelivery = `**Docker:** the simplest option is to re-index on the server host directly, so the
\`gitnexus-data\` volume stays fresh without any artifact handoff:

\`\`\`sh
# On the server, on a schedule (e.g. a cron entry):
# 0 * * * * cd /path/to/repo && npx gitnexus@latest analyze --skills
\`\`\`

Or download the CI artifact and copy it into the running container's volume:

\`\`\`sh
# gh run download --name "gitnexus-index-<sha>" --dir ./gitnexus-index
# docker compose cp ./gitnexus-index/. gitnexus:/data/gitnexus/
\`\`\``;

  const acaDelivery = `**Azure Container App:** push the index to the Azure File share the app mounts:

\`\`\`sh
# From a machine with ./.gitnexus and an \`az login\` session:
# az storage file upload-batch \\
#   --account-name "$STORAGE_ACCOUNT" \\
#   --destination "$FILE_SHARE" \\
#   --source ./.gitnexus
\`\`\``;

  const deliverySection =
    opts.deploy === 'azure-container-app'
      ? acaDelivery
      : opts.deploy === 'both'
        ? `${dockerDelivery}\n\n${acaDelivery}`
        : dockerDelivery;

  return `# GitNexus — Shared Code Intelligence Server

GitNexus builds a knowledge graph of this repository and serves it as an MCP (Model Context Protocol)
server, giving AI coding assistants (Claude Code, Cursor, etc.) deep understanding of call graphs,
execution flows, and blast-radius impact — without reading every file on every request.

> **License**: PolyForm-Noncommercial-1.0.0 — commercial use requires a separate agreement.
> Confirm this deployment is non-commercial, or contact the maintainer before use in client environments.
> Copyright: Abhigyan Patwari. [PolyForm](https://polyformproject.org/licenses/noncommercial/1.0.0/)

---

## Setup decisions

| Decision | Choice | Rationale |
|---|---|---|
| CI/CD system | ${ciLabel} | ${detect.detectedCi ? 'Auto-detected from existing workflow files' : 'Selected during ci-setup'} |
| Deployment target | ${deployLabel} | Selected during ci-setup |
| Auth model | ${authLabel} | ${opts.auth === 'token' ? 'Prevents unauthorized access to indexed source code' : 'Deployment behind trusted network perimeter'} |
| Branch index strategy | ${branchLabel} | ${opts.branchStrategy === 'pr-scoped' ? 'Keeps AI clients aware of in-progress work on open PRs' : 'Simpler; indexes only merged code'} |
| Server port | ${opts.port} | Default \`gitnexus serve\` port |
${opts.auth === 'token' ? `| Proxy port | ${caddyProxyPort(opts)} | Caddy listens here; gitnexus is internal-only |\n` : ''}
---

## Connecting your AI client

${connectSection}

---

## Triggering a manual re-index

From inside the repository root:

\`\`\`sh
npx gitnexus@latest analyze --skills
\`\`\`

To force a full re-index (ignores cached state):

\`\`\`sh
npx gitnexus@latest analyze --skills --force
\`\`\`

---

## Skill files

When the CI workflow runs \`analyze --skills\`, GitNexus generates repo-specific skill files in:

- \`.claude/skills/gitnexus/\` — standard GitNexus MCP skills (query, impact, context, detect-changes)
- \`.claude/skills/generated/\` — community-detected area skills (one file per functional cluster)

The CI workflow generates these on the runner but does **not** commit them — it runs with \`permissions: contents: read\`. To share them with your team, commit them manually after a run, or add a \`git add .claude/skills/ && git commit && git push\` step to the workflow (which also requires granting it \`permissions: contents: write\`).

---

## Index staleness policy

The CI workflow uploads the \`.gitnexus/\` directory as a workflow artifact (30-day retention) on every run.
If the index is stale (CI hasn't run since the last push), Claude Code will still function but may operate
on a slightly outdated graph. The "Verify index was produced" step fails the run only if \`analyze\`
produced no output — it does not compare the index against the current commit, so it does not detect
or block stale-index PRs.

> **The wizard does not automate index delivery to the shared server.** CI uploads \`.gitnexus/\` as a
> workflow artifact; the running server reads its own persistent volume, and nothing connects the two
> automatically. Delivering the fresh index to the server's volume is a required operator step — pick
> the approach that matches your deployment (the commands below are commented; adapt paths/names):

${deliverySection}

---

## Generated files

| File | Purpose |
|---|---|
${opts.ci === 'github-actions' || opts.ci === 'both' ? '| `.github/workflows/gitnexus-ci.yml` | Keeps the index fresh on every push and PR |\n' : ''}${opts.ci === 'azure-devops' || opts.ci === 'both' ? '| `azure-pipelines-gitnexus.yml` | Azure DevOps equivalent |\n' : ''}${opts.deploy === 'docker' || opts.deploy === 'both' ? '| `docker-compose.gitnexus.yml` | Runs the shared gitnexus serve container |\n' : ''}${opts.auth === 'token' && (opts.deploy === 'docker' || opts.deploy === 'both') ? '| `Caddyfile` | Caddy reverse proxy config (token enforcement) |\n' : ''}${opts.deploy === 'azure-container-app' || opts.deploy === 'both' ? '| `gitnexus-aca-deploy.sh` | Azure Container App deployment script |\n' : ''}| \`.claude/gitnexus-mcp-snippet.json\` | HTTP MCP entry for the shared server |
`;
}

export function generateFiles(opts: CiSetupOptions, detect: DetectResult): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  if (opts.ci === 'github-actions' || opts.ci === 'both') {
    files.push({
      relativePath: '.github/workflows/gitnexus-ci.yml',
      content: buildGitHubActionsWorkflow(opts),
    });
  }

  if (opts.ci === 'azure-devops' || opts.ci === 'both') {
    files.push({
      relativePath: 'azure-pipelines-gitnexus.yml',
      content: buildAzurePipelineYaml(opts),
    });
  }

  if (opts.deploy === 'docker' || opts.deploy === 'both') {
    files.push({
      relativePath: 'docker-compose.gitnexus.yml',
      content: buildDockerCompose(opts),
    });
    if (opts.auth === 'token') {
      files.push({
        relativePath: 'Caddyfile',
        content: buildCaddyfile(opts),
      });
    }
  }

  if (opts.deploy === 'azure-container-app' || opts.deploy === 'both') {
    files.push({
      relativePath: 'gitnexus-aca-deploy.sh',
      content: buildAcaDeployScript(opts),
    });
  }

  files.push({
    relativePath: '.claude/gitnexus-mcp-snippet.json',
    content: buildMcpSnippet(opts),
  });

  files.push({
    relativePath: 'GITNEXUS.md',
    content: buildGitnexusMd(opts, detect),
  });

  return files;
}
