/** Fixed answers reviewed from the fixture source, never learned from tool output. */
export const EXPECTATIONS = [
  {
    id: 'rename.references',
    issue: 3486,
    title: 'All resolved Writer.close references',
    expected: [
      'rename/caller.ts:3:writer.closeWriter();',
      'rename/writer.ts:2:closeWriter(): void {}',
      'rename/writer.ts:8:writer.closeWriter();',
    ],
  },
  {
    id: 'rename.comments-strings',
    issue: 3486,
    title: 'Comments and strings receive no edits',
    expected: [],
  },
  {
    id: 'rename.homonyms',
    issue: 3486,
    title: 'Unrelated methods and functions receive no edits',
    expected: [],
  },
  {
    id: 'routes.production-handler',
    issue: 3487,
    title: 'Test stub cannot replace the server handler',
    expected: ['GET /api/info src/server/api.ts'],
  },
  {
    id: 'routes.all-method',
    issue: 3487,
    title: 'Express app.all is method agnostic',
    expected: ['* /api/mcp src/server/api.ts'],
  },
  { id: 'routes.map-lookup', issue: 3487, title: 'Map.get is not an HTTP route', expected: [] },
  {
    id: 'routes.helper-registration',
    issue: 3487,
    title: 'Literal route forwarded through a local helper',
    expected: ['GET /api/progress src/server/api.ts'],
  },
  {
    id: 'api.template-wrapper',
    issue: 3488,
    title: 'Base URL template passed to a fetch wrapper is a consumer',
    expected: ['src/web/client.ts'],
  },
  {
    id: 'api.literal-control',
    issue: 3488,
    title: 'Direct literal fetch consumer control',
    expected: ['src/web/control.ts'],
  },
  {
    id: 'explain.named-flow',
    issue: 3489,
    title: 'Named request handler reaches the command sink',
    expected: ['handleUnsafe -> runGit command-injection'],
  },
  {
    id: 'explain.inline-flow',
    issue: 3489,
    title: 'Inline request callback reaches the command sink',
    expected: ['src/server/inline.ts -> runGit command-injection'],
  },
  {
    id: 'explain.guard',
    issue: 3490,
    title: 'Strict SHA allow-list prevents command injection',
    expected: [],
  },
  {
    id: 'explain.constant-control',
    issue: 3490,
    title: 'Constant command has no request taint',
    expected: [],
  },
  {
    id: 'explain.cross-lines',
    issue: 3491,
    title: 'Cross-function source, sink and every hop are 1-based',
    expected: [
      'source handleUnsafe@14',
      'sink runGit@4',
      'hop 0 handleUnsafe@14',
      'hop 1 blameSummary@7',
      'hop 2 runGit@4',
    ],
  },
  {
    id: 'explain.intra-lines',
    issue: 3491,
    title: 'Statement-level source, sink and hops are 1-based',
    expected: [
      'function@22',
      'source command@23',
      'sink@24',
      'hop 0 command@23',
      'hop 1 command@24',
    ],
  },
  {
    id: 'python.module-direct',
    issue: 3497,
    title: 'Direct imported-module receiver control',
    expected: ['pkg/facade.py:target'],
  },
  {
    id: 'python.module-chain',
    issue: 3497,
    title: 'Module-return helper chained receiver',
    expected: ['pkg/facade.py:target'],
  },
  {
    id: 'python.module-local',
    issue: 3497,
    title: 'Module-return helper assigned to a local',
    expected: ['pkg/facade.py:target'],
  },
  {
    id: 'python.factory-direct',
    issue: 3498,
    title: 'Annotated factory direct assignment control',
    expected: ['mod.py:C.m'],
  },
  {
    id: 'python.factory-conditional',
    issue: 3498,
    title: 'Annotated factory through conditional expression',
    expected: ['mod.py:C.m'],
  },
  {
    id: 'python.factory-qualified',
    issue: 3498,
    title: 'Annotated factory through module alias',
    expected: ['mod.py:C.m'],
  },
  {
    id: 'python.factory-boolean',
    issue: 3498,
    title: 'Annotated factory through boolean expression',
    expected: ['mod.py:C.m'],
  },
  {
    id: 'python.nested-local-import',
    issue: 3499,
    title: 'Function-local import beats unrelated nested declaration',
    expected: ['pkg/facade.py:target'],
  },
  {
    id: 'python.nested-module-import',
    issue: 3499,
    title: 'Module import beats unrelated nested declaration',
    expected: ['pkg/facade.py:target'],
  },
  {
    id: 'python.nested-unbound',
    issue: 3499,
    title: 'Sibling cannot call an out-of-scope nested declaration',
    expected: [],
  },
  {
    id: 'python.local-import-control',
    issue: 3499,
    title: 'Function-local import without homonym control',
    expected: ['pkg/facade.py:target'],
  },
  {
    id: 'python.local-import-leak',
    issue: 3499,
    title: 'Function-local import cannot bind a sibling function',
    expected: [],
  },
  {
    id: 'summary.exact-control',
    issue: 3497,
    title: 'Complete empty drop summary permits exact',
    expected: ['exact'],
  },
  {
    id: 'summary.retained-lower-bound',
    issue: 3497,
    title: 'Retained dropped name requires lower-bound',
    expected: ['lower-bound'],
  },
  {
    id: 'summary.cap',
    issue: 3497,
    title: '501 names retain 500 and explicitly omit the last name',
    expected: ['kept=500 total=1001 omitted=1 target=false'],
  },
  {
    id: 'summary.omitted-lower-bound',
    issue: 3497,
    title: 'Absent name in a truncated summary cannot claim exact',
    expected: ['lower-bound'],
  },
] satisfies Array<{ id: string; issue: number; title: string; expected: string[] }>;
