/**
 * Nuxt v4 auto-import resolution for the TypeScript scope-resolver.
 *
 * Nuxt and Nitro both make symbols available project-wide without explicit
 * import statements. Two sources cover the common cases:
 *
 *   1. `.nuxt/imports.d.ts` - client/shared composables generated by Nuxt at
 *      build time. Only entries whose source is a project-local relative path
 *      (i.e. NOT a package in node_modules or a Nuxt runtime alias) are
 *      indexed. These are project utils and composables the developer wrote.
 *
 *   2. `server/utils/**` - Nitro auto-imports all exports from this directory
 *      tree into every `server/api/`, `server/routes/`, and
 *      `server/middleware/` file. These are not included in `imports.d.ts`
 *      because they are server-only.
 *
 * Both sources produce the same `NuxtAutoImportEntry` shape so the edge-
 * emission pass can treat them uniformly.
 *
 * Detection: if `.nuxt/imports.d.ts` is absent the repo is not a Nuxt project
 * and this module returns null immediately, adding zero overhead to non-Nuxt
 * analysis runs. The `server/utils` scan is only attempted when the Nuxt
 * detection succeeds, so it also costs nothing for non-Nuxt repos.
 *
 * Limitations:
 *   - Calls inside string literals or single-line comments are not excluded
 *     by the content scanner. False-positive edges are tagged with
 *     confidence 0.75 to signal that they are heuristic, not type-checked.
 *   - Re-exports with non-matching aliases (e.g. `flatUnwrap as unwrapSlot`
 *     where `flatUnwrap` is the graph node name) try both the original export
 *     name and the local alias when looking up the graph node.
 *   - Only direct exports are indexed; barrel re-exports that chain through
 *     multiple files are not followed.
 */

import fs from 'fs/promises';
import path from 'path';

// ---- types ------------------------------------------------------------------

/** A single auto-imported symbol and where it lives in the repo. */
export interface NuxtAutoImportEntry {
  /** The name used at call sites (the alias when `export { X as Y }` form). */
  readonly localName: string;
  /** The original export name in the source file (before `as`). */
  readonly exportName: string;
  /** Repo-relative POSIX path to the source file (with extension). */
  readonly sourceFile: string;
}

/**
 * Aggregated auto-import map for one Nuxt workspace, keyed by the local
 * name used in calling code.
 */
export interface NuxtAutoImportConfig {
  readonly byLocalName: ReadonlyMap<string, NuxtAutoImportEntry>;
}

// ---- loader -----------------------------------------------------------------

/**
 * Load the Nuxt auto-import map for `repoRoot`.
 *
 * Returns null when:
 *   - `.nuxt/imports.d.ts` does not exist (non-Nuxt project or pre-build), or
 *   - the file exists but yields zero project-local entries and `server/utils`
 *     is absent or empty.
 *
 * The `server/utils` scan is only attempted when `.nuxt/imports.d.ts` was
 * successfully read, confirming this is an initialized Nuxt project. This
 * avoids partial results from repos that have a `server/utils` directory but
 * are not Nuxt projects.
 */
export async function loadNuxtAutoImports(repoRoot: string): Promise<NuxtAutoImportConfig | null> {
  const byLocalName = new Map<string, NuxtAutoImportEntry>();

  const nuxtInitialized = await collectImportsDts(repoRoot, byLocalName);

  // Only scan server/utils when imports.d.ts was present, confirming this is
  // an initialized Nuxt project. Without this gate, a non-Nuxt repo with a
  // server/utils directory would get spurious Nitro auto-import edges.
  if (nuxtInitialized) {
    await collectNitroServerUtils(repoRoot, byLocalName);
  }

  return byLocalName.size > 0 ? { byLocalName } : null;
}

// ---- .nuxt/imports.d.ts -----------------------------------------------------

/**
 * Parse `.nuxt/imports.d.ts` and add project-local entries to `byLocalName`.
 *
 * The file contains lines of the form:
 *   export { name1, name2, origName as alias } from 'source'
 *
 * Only entries with a source that is a project-local relative path
 * (starts with `./` or `../` AND does not contain `node_modules`) are
 * included. Nuxt runtime paths (`#app/...`) and third-party packages are
 * intentionally skipped because they have no graph nodes in the repo.
 */
/** Returns true when `.nuxt/imports.d.ts` was successfully read. */
async function collectImportsDts(
  repoRoot: string,
  byLocalName: Map<string, NuxtAutoImportEntry>,
): Promise<boolean> {
  const importsPath = path.join(repoRoot, '.nuxt', 'imports.d.ts');
  let content: string;
  try {
    content = await fs.readFile(importsPath, 'utf-8');
  } catch {
    return false;
  }

  const nuxtDir = path.join(repoRoot, '.nuxt');
  // Matches: export { name1, name2 as alias } from 'source'
  const lineRe = /^export\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"]/gm;
  let m: RegExpExecArray | null;

  while ((m = lineRe.exec(content)) !== null) {
    const symbolsRaw = m[1]!;
    const source = m[2]!;

    if (!isProjectLocalPath(source)) continue;

    const resolvedFile = await resolveExtension(path.resolve(nuxtDir, source));
    if (resolvedFile === null) continue;

    const sourceFile = toRepoPosix(repoRoot, resolvedFile);

    for (const raw of symbolsRaw.split(',')) {
      const trimmed = raw.trim();
      if (!trimmed) continue;

      const asIdx = trimmed.indexOf(' as ');
      const exportName = asIdx >= 0 ? trimmed.slice(0, asIdx).trim() : trimmed;
      const localName = asIdx >= 0 ? trimmed.slice(asIdx + 4).trim() : trimmed;

      if (!localName || !exportName) continue;

      if (!byLocalName.has(localName)) {
        byLocalName.set(localName, { localName, exportName, sourceFile });
      }
    }
  }
  return true;
}

// ---- server/utils (Nitro auto-imports) --------------------------------------

/**
 * Scan `server/utils/**` and register every exported symbol as a Nitro
 * auto-import. Nitro makes all exports from this directory tree available
 * without an import statement in server routes and middleware.
 */
async function collectNitroServerUtils(
  repoRoot: string,
  byLocalName: Map<string, NuxtAutoImportEntry>,
): Promise<void> {
  const serverUtilsDir = path.join(repoRoot, 'server', 'utils');
  if (!(await dirExists(serverUtilsDir))) return;

  const tsFiles = await collectTsFiles(serverUtilsDir);

  for (const absPath of tsFiles) {
    let content: string;
    try {
      content = await fs.readFile(absPath, 'utf-8');
    } catch {
      continue;
    }

    const sourceFile = toRepoPosix(repoRoot, absPath);

    // Match top-level exported functions and constants.
    // Handles: export function X, export async function X, export const X =
    // Does NOT attempt to match re-exports from other modules.
    const exportRe =
      /^export\s+(?:async\s+)?function\s+(\w+)|^export\s+const\s+(\w+)\s*[=:]/gm;
    let m: RegExpExecArray | null;

    while ((m = exportRe.exec(content)) !== null) {
      const name = (m[1] ?? m[2])!;
      if (!byLocalName.has(name)) {
        byLocalName.set(name, { localName: name, exportName: name, sourceFile });
      }
    }
  }
}

// ---- helpers ----------------------------------------------------------------

function isProjectLocalPath(source: string): boolean {
  if (!source.startsWith('./') && !source.startsWith('../')) return false;
  if (source.includes('node_modules')) return false;
  return true;
}

async function resolveExtension(base: string): Promise<string | null> {
  for (const ext of ['.ts', '.tsx', '.js', '.jsx', '']) {
    const candidate = ext ? base + ext : base;
    try {
      await fs.access(candidate);
      return candidate;
    } catch {
      // try next
    }
  }
  return null;
}

function toRepoPosix(repoRoot: string, absPath: string): string {
  return path.relative(repoRoot, absPath).replace(/\\/g, '/');
}

async function dirExists(dirPath: string): Promise<boolean> {
  try {
    const stat = await fs.stat(dirPath);
    return stat.isDirectory();
  } catch {
    return false;
  }
}

/** Recursively collect `.ts` and `.tsx` files under a directory. */
async function collectTsFiles(dir: string): Promise<string[]> {
  const results: string[] = [];
  let entries: import('fs').Dirent[];
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...(await collectTsFiles(full)));
    } else if (entry.isFile() && (entry.name.endsWith('.ts') || entry.name.endsWith('.tsx'))) {
      results.push(full);
    }
  }
  return results;
}
